Shamelessly copied multi file support from randy3k/rmate

diff --git a/rmate b/rmate
--- a/rmate
+++ b/rmate
@@ -3,7 +3,7 @@
 # Petonic version {2016-11-20 SUN 12:54} 
 #
 # rmate
-# Copyright (C) 2011-2016 by Harald Lapp <harald@octris.org>
+# Copyright (C) 2011-2015 by Harald Lapp <harald@octris.org>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -35,8 +35,8 @@
 
 # init
 #
-version="0.9.8"
-version_date="2016-04-14"
+version="0.9.6"
+version_date="2015-09-15"
 version_string="rmate-sh $version ($version_date)"
 
 # determine hostname
@@ -59,7 +59,6 @@ hostname=$($(hostname_command))
 # default configuration
 host=localhost
 port=52698
-eval home=$(builtin printf "~%q" "${SUDO_USER:-$LOGNAME}")
 
 function load_config {
     local rc_file=$1
@@ -79,7 +78,7 @@ function load_config {
     fi
 }
 
-for i in "/etc/${0##*/}" $home/."${0##*/}/${0##*/}.rc" $home/."${0##*/}.rc"; do
+for i in "/etc/${0##*/}" ~/."${0##*/}/${0##*/}.rc" ~/."${0##*/}.rc"; do
     load_config $i
 done
 
@@ -88,10 +87,10 @@ port="${RMATE_PORT:-$port}"
 
 
 # misc initialization
-filepath=""
-selection=""
-displayname=""
-filetype=""
+filepaths=()
+displaynames=()
+selections=()
+filetypes=()
 verbose=false
 nowait=true
 force=false
@@ -107,7 +106,6 @@ function showusage {
 -p, --port PORT  Port number to use for connection. Defaults to $port.
 -w, --[no-]wait  Wait for file to be closed by TextMate.
 -l, --line LINE  Place caret on line number after loading file.
-+N               Alias for --line, if N is a number (eg.: +5).
 -m, --name NAME  The display name shown in TextMate.
 -t, --type TYPE  Treat file as having specified type.
 -n, --new        Open in a new window (Sublime Text).
@@ -145,7 +143,7 @@ function canonicalize {
     echo $result
 }
 
-while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
+while test "${1:0:1}" = "-"; do
     case $1 in
         -)
             break
@@ -165,15 +163,15 @@ while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
             nowait=true
             ;;
         -l|--line)
-            selection=$2
+            selections+=($2)
             shift
             ;;
         -m|--name)
-            displayname=$2
+            displaynames+=($2)
             shift
             ;;
         -t|--type)
-            filetype=$2
+            filetypes+=($2)
             shift
             ;;
         -n|--new)
@@ -193,9 +191,6 @@ while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
             showusage
             exit 1
             ;;
-        +[0-9]*)
-            selection=${1:1}
-            ;;
         *)
             showusage
             exit 1
@@ -209,11 +204,11 @@ if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
     host=${SSH_CONNECTION%% *}
 fi
 
-filepath="$1"
+filepaths=("$@")
 
-if [ "$filepath" = "" ]; then
+if [ "$filepaths" = "" ]; then
     if [[ $nowait = false ]]; then
-        filepath='-'
+        filepaths='-'
     else
         case "$-" in
             *i*)
@@ -221,45 +216,93 @@ if [ "$filepath" = "" ]; then
                 exit 1
                 ;;
             *)
-                filepath='-'
+                filepaths='-'
                 ;;
         esac
     fi
 fi
 
-shift
-if [ ! "${#@}" -eq 0 ]; then
-    echo "There is more than one file specified. Opening only $filepath and ignoring other."
-fi
-
-if [ "$filepath" != "-" ]; then
-    realpath=`canonicalize "$filepath"`
-    log $realpath
-
-    if [ -d "$filepath" ]; then
-        echo "$filepath is a directory and rmate is unable to handle directories."
-        exit 1
-    fi
-
-    if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
-        if [[ $force = false ]]; then
-            echo "File $filepath is not writable! Use -f to open anyway."
-            exit 1
-        elif [[ $verbose = true ]]; then
-            log "File $filepath is not writable! Opening anyway."
-        fi
-    fi
-
-    if [ "$displayname" = "" ]; then
-        displayname="$hostname:$filepath"
-    fi
-else
-    displayname="$hostname:untitled"
-fi
 
 #------------------------------------------------------------
 # main
 #------------------------------------------------------------
+
+function open_file {
+
+    index="$1"
+    filepath="${filepaths[$index]}"
+    selection="${selections[$index]}"
+    filetype="${filetypes[$index]}"
+    displayname="${displaynames[$index]}"
+
+    if [ "$filepath" != "-" ]; then
+        realpath=`canonicalize "$filepath"`
+        log $realpath
+
+        if [ -d "$filepath" ]; then
+            echo "$filepath is a directory and rmate is unable to handle directories."
+            exit 1
+        fi
+
+        if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
+            if [[ $force = false ]]; then
+                echo "File $filepath is not writable! Use -f to open anyway."
+                exit 1
+            elif [[ $verbose = true ]]; then
+                log "File $filepath is not writable! Opening anyway."
+            fi
+        fi
+
+        if [ "$displayname" = "" ]; then
+            displayname="$hostname:$filepath"
+        fi
+    else
+        displayname="$hostname:untitled"
+    fi
+
+    echo "open" 1>&3
+    echo "display-name: $displayname" 1>&3
+    echo "real-path: $realpath" 1>&3
+    echo "data-on-save: yes" 1>&3
+    echo "re-activate: yes" 1>&3
+    echo "token: $filepath" 1>&3
+
+    if [[ $new = true ]]; then
+        echo "new: yes"  1>&3
+    fi
+
+    if [ "$selection" != "" ]; then
+        echo "selection: $selection" 1>&3
+    fi
+
+    if [ "$filetype" != "" ]; then
+        echo "file-type: $filetype" 1>&3
+    fi
+
+    if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
+        filesize=`ls -lLn "$realpath" | awk '{print $5}'`
+        echo "data: $filesize" 1>&3
+        cat "$realpath" 1>&3
+    elif [ "$filepath" = "-" ]; then
+        if [ -t 0 ]; then
+            echo "Reading from stdin, press ^D to stop"
+        else
+            log "Reading from stdin"
+        fi
+
+        # preserve trailing newlines
+        data=`cat; echo x`
+        data=${data%x}
+        filesize=$(echo -ne "$data" | wc -c)
+        echo "data: $filesize" 1>&3
+        echo -n "$data" 1>&3
+    else
+        echo "data: 0" 1>&3
+    fi
+
+    echo 1>&3
+}
+
 function handle_connection {
     local cmd
     local name
@@ -337,47 +380,10 @@ read server_info 0<&3
 
 log $server_info
 
-echo "open" 1>&3
-echo "display-name: $displayname" 1>&3
-echo "real-path: $realpath" 1>&3
-echo "data-on-save: yes" 1>&3
-echo "re-activate: yes" 1>&3
-echo "token: $filepath" 1>&3
+for i in "${!filepaths[@]}"; do
+    open_file "$i"
+done
 
-if [[ $new = true ]]; then
-    echo "new: yes"  1>&3
-fi
-
-if [ "$selection" != "" ]; then
-    echo "selection: $selection" 1>&3
-fi
-
-if [ "$filetype" != "" ]; then
-    echo "file-type: $filetype" 1>&3
-fi
-
-if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
-    filesize=`ls -lLn "$realpath" | awk '{print $5}'`
-    echo "data: $filesize" 1>&3
-    cat "$realpath" 1>&3
-elif [ "$filepath" = "-" ]; then
-    if [ -t 0 ]; then
-        echo "Reading from stdin, press ^D to stop"
-    else
-        log "Reading from stdin"
-    fi
-
-    # preserve trailing newlines
-    data=`cat; echo x`
-    data=${data%x}
-    filesize=$(echo -ne "$data" | wc -c)
-    echo "data: $filesize" 1>&3
-    echo -n "$data" 1>&3
-else
-    echo "data: 0" 1>&3
-fi
-
-echo 1>&3
 echo "." 1>&3
 
 if [[ $nowait = true ]]; then
